version: "4.11"
services:
    app:
        build:
            args:
                user: admin
                uid: 123456
            context: ./
            dockerfile: Dockerfile
        image: php:8.1-fpm
        container_name: training_docker
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www/
        networks:
            - training_docker

    nginx:
        image: nginx:1.17-alpine
        container_name: training_nginx
        restart: unless-stopped
        working_dir: /var/www/
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/
            - ./Docker/nginx:/etc/nginx/conf.d
        networks:
            - training_docker


    db:
        image: bitnami/mysql:5.7.29-debian-10-r51
        container_name: training_mysql
        restart: unless-stopped
        ports:
            - "3308:3306"
        volumes:
            - ./Docker/mysql:/docker-entrypoint-init-db.d
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        networks:
            - training_docker

networks:
  training_docker:
    driver: bridge